<?php

$language['gallery']='Galerie';
$language['gallery1']='Tlačítko Galerie vám umožňuje přejít na stránku galerie, bez ohledu na to, kde jste.';
$language['gallery2']='Nahrát';
$language['gallery3']='Tlačítko Nahrát vám umožní nahrát obrázky, které chcete použít na webu. Při nahrávání obrázku na tento server, se musíte ujistit, že název souboru se nepoužívá v nesprávném tvaru. Všechny soubory nahrané takhle budou vymazány.';
$language['gallery4']='Zpět';
$language['gallery5']='Tlačítko Zpět vám umožní přejít zpět na předchozí stránku, kde jste byli dříve, než jste odešli.';
$language['gallery6']='Znovu';
$language['gallery7']='Znovu je totéž jako obnovení. Pokud potřebujete aktualizovat stránku klikněte na toto tlačítko, aniž byste ji museli zavřít a znovu otevřit. ';
$language['gallery8']='Nápověda';
$language['gallery9']='Tlačítkem Nápověda se dostanete do tohoto tutoriálu o tom, jak používat galerii stránky a co všechno dělá.';
$language['gallery10']='Zavřít';
$language['gallery11']='Tlačítko Zavřít zavře galerii.';
$language['gallery12']='Nahrát další soubor';
$language['gallery13']='Take Me To The Gallery';
$language['gallery14']='<font color="#ffffff">Picture Preview</font>';
$language['gallery15']='<font color="#ffffff"><b>Picture Gallery Upload<br>Please read the ReadMe to Understand How The Gallery Works</font>';
$language['gallery16']='<font color="#ffffff"><b>Picture Gallery Preview<br>Please read the ReadMe to Understand How The Gallery Works</font>';
$language['gallery17']='<font color="#ffffff">Success! <br> Click the following URL to access your picture.</font>';
$language['gallery18']='Upload File';
$language['gallery19']='<b>Sorry,</b><br> Not possible to delete this <b>READ ONLY</b> file  from the Gallery Folder. <p> Please contact the staff to set proper folder permissions and delete file.';
$language['gallery20']='<font color="#ffff00" class="small">Disclaimer:<br>Do not upload unauthorized or Illegal Pictures.<br>Uploaded Pictures should be considered "Public Domain";</font><br><u><font color="red">Illegal Uploaded Pictures will result in a IMMEDIATE Ban</font></u></color>';
$language['gallery21']='<font color="#ffffff" class="small">Upload File</font>';
$language['gallery22']='<font color="#ffffff"><b>Upload Failed Sorry,<p> A file with the name already exists in the picture gallery preview page.<p> Click the BACK button to try again.</b></font>';
$language['gallery23']='<font color="#ffffff"><b>Error:</b><p> Your image has not been uploaded. <p> The extension has not been recognized. Please try again. <p> Click the BACK button to try again.</font>';
$language['gallery24']='<font color="#ffffff"><b>File size is too large. <p> Reduce the file size and try it again.<p> Click the BACK button to try again.</b></font>';
$language['gallery25']='<font color="#ffffff"><b>GALLERY README</b> <br>Please read Each Column to Understand How The Gallery Works</font>';
$language['gallery26']='<font color="#ffffff"><b>GALLERY IS EMPTY</b></font>';
$language['gallery27']='<font color="#ffffff"><b>Date</b></font>';
$language['gallery28']='<font color="#ffffff"><b>Time</b></font>';
$language['gallery29']='<font color="#ffffff"><b>Uploader</b></font>';
$language['gallery30']='<font color="#ffffff"><b>Filename</b></font>';
$language['gallery31']='<font color="#ffffff"><b>Image</b></font>';
$language['gallery32']='<font color="#ffffff"><b>Moderator</b></font>';
$language['gallery33']='[Delete]';
$language['gallery34']='<font color=#0000FF>Right Click on the URL Name given and select COPY SHORTCUT (Internet Explorer) or COPY LINK LOCATION (Mozilla FireFox). <br>Now right click again and select PASTE to paste the URL where you want to use it.  You can also use the keyboard commands CTRL C to COPY and CTRL V to PASTE as well.</font>';
$language['gallery35']='<font color="#FFFFFF">Menu System</font>';
$language['gallery36']='Browse';
$language['gallery37']='Picture Format';
$language['gallery38']='Click the browse button to select the file you want to upload. <br> The following picture extensions are authorized to be uploaded <b>*.gif, *.GIF, *.jpg, *.JPG, *.jpeg, *.JPEG, *.png, *.PNG</b> only.';
$language['gallery39']='File Upload Button is selected when you are ready to upload your picture.';
$language['gallery40']='The Date the picture was uploaded.';
$language['gallery41']='The Time the picture was uploaded';
$language['gallery42']='Uploader is the user who uploaded the file';
$language['gallery43']='Filename is the name of the file with URL that can be used on the site.  Scroll your mouse over the link for further instructions on how to paste the url code.';
$language['gallery44']='Image is a preview of the picture added.  Click the picture for a larger view.';
$language['gallery45']='[CopyUrl]';

?>