<?php
global $users, $torrents, $seeds, $leechers, $percent;
// $language['rtl']='rtl'; // if your language is  right to left then uncomment this line
// $language['charset']='UTF-8'; // uncomment this line with specific language charset if different than tracker's one
$language['ACCOUNT_CONFIRM']='Ověřovací Email ze sítě '.$SITENAME.'.';
$language['ACCOUNT_CONGRATULATIONS']='Gratujeme Váš účet byl Aktivován!<br /> Nyní se můžete <a href="index.php?page=login">Přihlásit</a> na tracker prostřednictvím Vašeho účtu.';
$language['ACCOUNT_CREATE']='Vytvořit účet';
$language['ACCOUNT_DELETE']='Smazat účet';
$language['ACCOUNT_DETAILS']='Detaily účtu';
$language['ACCOUNT_EDIT']='Editovat účet';
$language['ACCOUNT_MGMT']='Nastavení účtu';
$language['ACCOUNT_MSG']='Ahoj,'."\n\n".' Tento Email byl zaslán někým kdo si chtěl založit účet na našem trackeru a v registraci použil tuto Emailovou adresu.'."\n".'Pokud jste o účet nežádali prosím ignorujte tento Email, V opačném případě potvrďte svůj účet.'."\n\n".'S pozdravem Modteam Besttrackeru.';
$language['ACTION']='Akce';
$language['ACTIVATED']='Aktiv';
$language['ACTIVE']='Status';
$language['ACTIVE_ONLY']='Aktiv pouze';
$language['ADD']='Přidat';
$language['ADDED']='Přidáno';
$language['ADMIN_CPANEL']='Admin panel';
$language['ADMINCP_NOTES']='Tady můžete kontrolovat všechna nastavení Trackeru...';
$language['ALL']='Vše';
$language['ALL_SHOUT']='All Shouts';
$language['ANNOUNCE_URL']='URL announce Trackeru:';
$language['ANONYMOUS']='Anonymní';
$language['ANSWER']='Odpověď';
$language['AUTHOR']='Autor';
$language['AVATAR_URL']='Avatar (url): ';
$language['AVERAGE']='Průměr';
$language['BACK']='Zpět';
$language['BAD_ID']='Špatné ID!';
$language['BCK_USERCP']='Zpět do Uživatelského panelu';
$language['BLOCK']='Block';
$language['BODY']='Text';
$language['BOTTOM']='bottom';
$language['BY']='Kým';
$language['CANT_DELETE_ADMIN']='Není možné smazat jiného admina!';
$language['CANT_DELETE_NEWS']='Nemáte oprávnění smazat novinky!';
$language['CANT_DELETE_TORRENT']='Nemáte oprávnění smazat tento torrent!...';
$language['CANT_DELETE_USER']='Nemáte oprávnění smazat Uživatele!';
$language['CANT_DO_QUERY']='Nemohu provést SQL dotaz - ';
$language['CANT_EDIT_TORR']='Nejste oprávněn editovat tento torrent!';
$language['CANT_FIND_TORRENT']='Nemohu najít torrent soubor!';
$language['CANT_READ_LANGUAGE']='Nemohu přečíst soubor language (jazyků)!';
$language['CANT_SAVE_CONFIG']='Nemohu uložit nastavení do config.php';
$language['CANT_SAVE_LANGUAGE']='Nemohu uložit sobory language (jazyků)';
$language['CANT_WRITE_CONFIG']='UPOZORNĚNÍ: Nemohu zapisovat config.php!';
$language['CATCHUP']='Označit vše jako přečtené';
$language['CATEGORY']='Kat.';
$language['CATEGORY_FULL']='Kategorie';
$language['CENTER']='Střed';
$language['CHANGE_PID']='Změnit PID';
$language['CHARACTERS']='characters';
$language['CHOOSE']='Zvolit';
$language['CHOOSE_ONE']='Zvolit jeden';
$language['CLICK_HERE']='Klikněte sem';
$language['CLOSE']='zavřít';
$language['COMMENT']='Kom.';
$language['COMMENT_1']='Komentář';
$language['COMMENT_PREVIEW']='Náhled komentáře';
$language['COMMENTS']='Komentáře';
$language['CONFIG_SAVED']='Gratulujeme]= nové nastavení bylo ULOŽENO';
$language['COUNTRY']='Země';
$language['CURRENT_DETAILS']='Aktuální Detaily';
$language['DATABASE_ERROR']='Databáze error.';
$language['DATE']='Datum';
$language['DB_ERROR_REQUEST']='Databáze error. Nemohu dokončit požadavek.';
$language['DB_SETTINGS']='Nastavení Databáze';
$language['DEAD_ONLY']='Mrtvé pouze';
$language['DELETE']='Smazat';
$language['DELETE_ALL_READED']='Smazat všechny přečtené';
$language['DELETE_CONFIRM']='Jste si jistý že toto chcete Smazat/Odstranit?';
$language['DELETE_TORRENT']='Smazat Torrent';
$language['DELFAILED']='Smazání selhalo';
$language['DESCRIPTION']='Popis';
$language['DONT_NEED_CHANGE']='Nepotřebujete měnit toto nastavení!';
$language['DOWN']='Dl';
$language['DOWNLOAD']='Stáhnout';
$language['DOWNLOAD_TORRENT']='Stáhnout Torrent';
$language['DOWNLOADED']='Stáhnul';
$language['EDIT']='Editovat';
$language['EDIT_LANGUAGE']='Editovat Jazyk';
$language['EDIT_POST']='Editovat příspěvek';
$language['EDIT_TORRENT']='Editovat Torrent';
$language['EMAIL']='Email';
$language['EMAIL_SENT']='Ověřovací Email byl zaslalán na uvedenou Adresu<br />Klikněte na vložený odkaz pro aktivaci Vašeho účtu.';
$language['EMAIL_VERIFY']='email account update at '.$SITENAME;
$language['EMAIL_VERIFY_BLOCK']='Ověřovací email odeslán';
$language['EMAIL_VERIFY_MSG']='Ahoj'."\n\n".'Tento email byl zaslán protože požadujete změny emailové adresy aktuálně vedené v našech záznamech]= prosím klikněte na následující odkaz pro provedení změn.'."\n\n".'S pozdravem Modteam Besttrackeru.';
$language['EMAIL_VERIFY_SENT1']='<br /><center>Ověřovací email byl odeslán na:<br /><br /><strong><font color="red">';
$language['EMAIL_VERIFY_SENT2']='</font></strong><br /><br />Měli by jste kliknout na odkaz obsahující požadavanou změnu emailu<br />pro Update Vašeho emailu. Email by měl přijít do 10 minut<br />(většinou okamžitě) ovšem někteří provozovatelé emailů jej považují za SPAM <br />sproto SPAM koš zkontrolujte možná zde email najdete.<br /><br />';
$language['ERR_500']='HTTP/1.0 500 nepovolený přístup!';
$language['ERR_AVATAR_EXT']='Sorry pouze gif]=jpg]=bmp nebo png jsou povoleny';
$language['ERR_BAD_LAST_POST']='';
$language['ERR_BAD_NEWS_ID']='Špatné ID novinek!';
$language['ERR_BODY_EMPTY']='Body nemůže být prázdné!';
$language['ERR_CANT_CONNECT']='Nemohu se připojit k lokálnímu MySQL server';
$language['ERR_CANT_OPEN_DB']='Nemohu otevřit databázi';
$language['ERR_DB_ERR']='Databáze error. Prosím kontaktujte Administrátora s tímto problémem.';
$language['ERR_DELETE_POST']='Smazat příspěvek. Sanity check: You are about to delete a post. Click';
$language['ERR_DELETE_TOPIC']='Smazat topic. Sanity check: You are about to delete a topic. Click';
$language['ERR_EMAIL_ALREADY_EXISTS']='Tento Email již v databázi EXISTUJE!';
$language['ERR_EMAIL_NOT_FOUND_1']='Emailová adresa';
$language['ERR_EMAIL_NOT_FOUND_2']='nebyla nalezena v naší databázi.';
$language['ERR_ENTER_NEW_TITLE']='Musíte zadat nový název!';
$language['ERR_FORUM_NOT_FOUND']='Fórum nebylo nalezeno';
$language['ERR_FORUM_UNKW_ACT']='Forum Error: Neznámá akce';
$language['ERR_GUEST_EXISTS']='"Guest" je rezervované zakázané uživatelské jméno. Nemůžete se registrovat jako "Guest"';
$language['ERR_IMAGE_CODE']='Bezpečnostní kód nesouhlasí';
$language['ERR_INS_TITLE_NEWS']='Musíte vložit oboje název A novinky';
$language['ERR_INV_NUM_FIELD']='Neplatné číselné pole z klienta';
$language['ERR_INVALID_CLIENT_EVENT']='Neplatná událost= z klienta.';
$language['ERR_INVALID_INFO_BT_CLIENT']='Neplatné informace přijímané z BitTorrent klienta';
$language['ERR_INVALID_IP_NUMB']='Neplatná IP adresa. Musí být zadán s tečkami př 198.125. (provider není povolen)';
$language['ERR_LEVEL']='Sorry]= váš level ';
$language['ERR_LEVEL_CANT_POST']='Nemáte povolení příspěvků v tomto fóru.';
$language['ERR_LEVEL_CANT_VIEW']='Nemáte povolení zobrazení totoho topicu.';
$language['ERR_MISSING_DATA']='Chybějící data!';
$language['ERR_MUST_BE_LOGGED_SHOUT']='Musíš být přihlašený aby jsi mohl pokecat...';
$language['ERR_NO_BODY']='No body text';
$language['ERR_NO_NEWS_ID']='ID novinek nenalezeno!';
$language['ERR_NO_POST_WITH_ID']='Žádný příspěvek s tímto ID';
$language['ERR_NO_SPACE']='Vaše uživatelské jméno nesmí obsahovat mezeru]= prosím nahradtěte je:<br /><br />';
$language['ERR_NO_TOPIC_ID']='No Topic ID returned';
$language['ERR_NO_TOPIC_POST_ID']='Žádný topic není přiřazený ID příspěvku';
$language['ERR_NOT_AUTH']='Nemáte oprávnění!';
$language['ERR_NOT_FOUND']='Nenalezeno...';
$language['ERR_NOT_PERMITED']='Zakázáno';
$language['ERR_PASS_LENGTH']='<font color="black">Vaše heslo musí mít minimálně 4 znaky.</font>';
$language['ERR_PASSWORD_INCORRECT']='Nesprávné heslo';
$language['ERR_PERM_DENIED']='Povolení odepřeno';
$language['ERR_PID_NOT_FOUND']='Prosím stáhněte znova torrent soubory. PID systém je aktivnít a pid nebylo nalezeno v torrentu.';
$language['ERR_RETR_DATA']='Error retreaving data!';
$language['ERR_SEND_EMAIL']='Nemohu odeslat email. Prosím kontaktujte administrátory s touto chybou.';
$language['ERR_SERVER_LOAD']='Zatížení Serveru je velice vysoké v tuto chvili. ment. Opakujte později prosím...';
$language['ERR_SPECIAL_CHAR']='<font color="black">Vaše uživatelské jméno nemůže obsahovat speciální znaky jako:<br /><br /><font color="red"><strong>* &#63; &#60; &#62; &#64; &#36; &#38; &#37; etc.</strong></font></font><br />';
$language['ERR_SQL_ERR']='SQL Error';
$language['ERR_SUBJECT']='Musíte vložit předmět.';
$language['ERR_TOPIC_ID_NA']='Topic ID je N/A';
$language['ERR_TOPIC_LOCKED']='Topic je Uzamčen';
$language['ERR_TORRENT_IN_BROWSER']='Tento soubor je pro BitTorrent klienty.';
$language['ERR_UPDATE_USER']='Nemohu updatovat uživatelská data. Prosím kontaktujte administrátory s tímto problémem.';
$language['ERR_USER_ALREADY_EXISTS']='Tento nick je již používaný!';
$language['ERR_USER_NOT_FOUND']='Sorry]= Uživatel nenalezen';
$language['ERR_USER_NOT_USER']='Nemáte povolení vstupu do panelu jiných uživatelů!';
$language['ERR_USERNAME_INCORRECT']='Nesprávné Uživatelské jméno';
$language['ERROR']='Error';
$language['ERROR_ID']='Error ID';
$language['FACOLTATIVE']='doplňkový';
$language['FILE']='Soubor';
$language['FILE_CONTENTS']='Obsah souboru';
$language['FILE_NAME']='Jméno souboru';
$language['FIND_USER']='Najdi uživatele';
$language['FINISHED']='Hotovo';
$language['FORUM']='Forum';
$language['FORUM_ERROR']='Forum Error';
$language['FORUM_INFO']='Forum Info';
$language['FORUM_MIN_CREATE']='Min třída pro tvorbu';
$language['FORUM_MIN_READ']='Min třída pro čtení';
$language['FORUM_SEARCH']='Forum vyhledávání';
$language['FORUM_N_TOPICS']='Poč. Topiků';
$language['FORUM_N_POSTS']='Poč. Příspěvků';
$language['FRM_DELETE']='Smazat';
$language['FRM_LOGIN']='Přihlásit';
$language['FRM_PREVIEW']='Náhled';
$language['FRM_REFRESH']='Obnovit';
$language['FRM_RESET']='Resetovat';
$language['FRM_SEND']='Odeslat';
$language['FRM_CONFIRM']='Odeslat';
$language['FRM_CANCEL']='Zrušit';
$language['FRM_CLEAN']='vyčistit';
$language['GLOBAL_SERVER_LOAD']='Celkové zatížení serveru (Všechny weby na daném serveru)';
$language['GO']='Jdi';
$language['GROUP']='Skupina';
$language['GUEST']='Host'; 
$language['GUESTS']='Hosti';
$language['HERE']='Zde';
$language['HISTORY']='Historie';
$language['HOME']='Domů';
$language['IF_YOU_ARE_SURE']='Pokud jsi si jistý.';
$language['IM_SURE']='Jsem si jistý';
$language['IN']='v';
$language['INF_CHANGED']='Informace změněny!';
$language['INFINITE']='Inf.';
$language['INFO_HASH']='Info Hash';
$language['INS_NEW_PWD']='Vložte nové heslo!';
$language['INS_OLD_PWD']='Vložte staré heslo!';
$language['INSERT_DATA']='Vložte všechna potřebná data pro upload.';
$language['INSERT_NEW_FORUM']='Vložit nové forum';
$language['INVALID_ID']='Toto není platné ID. Sorry!';
$language['INVALID_INFO_HASH']='Neplatná info hash hodnota.';
$language['INVALID_PID']='Neplatný PID';
$language['INVALID_TORRENT']='Tracker error: neplatný torrent';
$language['KEYWORDS']='Klíčové slovo';
$language['LAST_EXTERNAL']='Update Externích Torrentů proběhl ';
$language['LAST_NEWS']='Poslední Novinky';
$language['LAST_POST_BY']='Poslední odesílatel';
$language['LAST_SANITY']='Poslední čištění trackeru proběhlo ';
$language['LAST_TORRENTS']='Nové torrenty';
$language['LAST_UPDATE']='Poslední Update';
$language['LASTPOST']='poslední odesilatel';
$language['LEECHERS']='Leechů';
$language['LEFT']='levo';
$language['LOGIN']='Přihlásit';
$language['LOGOUT']='Odhlásit';
$language['MAILBOX']='POŠTA';
$language['MANAGE_NEWS']='Spravovat novinky';
$language['MEMBER']='Uživatel';
$language['MEMBERS']='Uživatelů';
$language['MEMBERS_LIST']='Seznam uživatelů';
$language['MINIMUM_100_DOWN']='(s minimálně 100 MB staženými)';
$language['MINIMUM_5_LEECH']='s minimálně 5 leechery, nezapočítávají se mrtvé torrenty';
$language['MINIMUM_5_SEED']='s minimálně 5 seedery';
$language['MKTOR_INVALID_HASH']='makeTorrent: Received an invalid hash';
$language['MNU_ADMINCP']='ADMINISTRACE';
$language['MNU_FORUM']='Forum';
$language["STAFF"]="Náš Team";
$language['MNU_STAFF']='Team';
$language['MNU_INDEX']='Domů';
$language['MNU_MEMBERS']='Uživatelé';
$language['MNU_NEWS']='AKTUÁLNĚ';
$language['MNU_STATS']='Statistiky';
$language['MNU_TORRENT']='Torrenty';
$language['MNU_UCP_CHANGEPWD']='Změnit heslo';
$language['MNU_UCP_HOME']='Uživatelský panel';
$language['MNU_UCP_IN']='Vaše přijaté PM ';
$language['MNU_UCP_INFO']='Změnit profil';
$language['MNU_UCP_NEWPM']='Nová PM';
$language['MNU_UCP_OUT']='Vaše odeslané PM';
$language['MNU_UCP_PM']='Vaše PM Schránka';
$language['MNU_UPLOAD']='Upload';
$language['MORE_SMILES']='Více smajlíků';
$language['MORE_THAN']='Více než ';
$language['MORE_THAN_2']='items found]= displaying first';
$language['NA']='N/A';
$language['NAME']='Jméno';
$language['NEED_COOKIES']='Poznámka: Musíte mít zapnuté cookies pro přihlášení.';
$language['NEW_COMMENT']='Vložte svůj komentář...';
$language['NEW_COMMENT_T']='Nový komentá';
$language['NEWS']='Novinky';
$language['NEWS_DESCRIPTION']='Novinky:';
$language['NEWS_INSERT']='Vložte Vaše Novinky';
$language['NEWS_PANEL']=' Panel Novinky';
$language['NEWS_TITLE']='Název:';
$language['NEXT']='další';
$language['NO']='Ne';
$language['NO_BANNED_IPS']='Nejsou žádné banované IP';
$language['NO_COMMENTS']='Žádné komentáře...';
$language['NO_FORUMS']='Žádné Forum nebylo nalezeno!';
$language['NO_MAIL']='Nemáte žádný nový mail.';
$language['NO_MESSAGES']='Žádná PM nebyla nalezena...';
$language['NO_NEWS']='Žádné Novinky';
$language['NO_PEERS']='Žádné peery';
$language['NO_RECORDS']='Sorry]= ale seznam je prázdný...';
$language['NO_TOPIC']='Žádná témata nebyla nalezena';
$language['NO_TORR_UP_USER']='Žádné torrenty nebyly uploadnuty tímto uživatelem';
$language['NO_TORRENTS']='Zde nejsou žádné torrenty...';
$language['NO_USERS_FOUND']='Žádný uživatelé nebyli nalezení!';
$language['NOBODY_ONLINE']='Nikdo není online';
$language['NONE']='Nic';
$language['NOT_ADMIN_CP_ACCESS']='Nemáte oprávnění pro vstup do administračního panelu!';
$language['NOT_ALLOW_DOWN']='toto není povolené stáhnout z';
$language['NOT_AUTH_DOWNLOAD']=' Omlouváme se, ale nemáte uhrazený roční členský příspěvek 99,- Kč, z tohoto důvodu zatím nemáte možnost stahovat torrenty. Více informací najdete na stránce <a href="/index.php?page=prispevky"><font color="red"><h2>Příspěvky</h2></a>';
$language['NOT_AUTH_VIEW_NEWS']='Nemáte oprávnění pro zobrazení novinek!';
$language['NOT_AUTHORIZED']='Nemáte oprávnění pro zobrazení';
$language['NOT_AUTHORIZED_UPLOAD']='Nemáte oprávnění pro upload!';
$language['NOT_AVAILABLE']='N/A';
$language['NOT_MAIL_IN_URL']='Toto není emailová adresa která byla v této URL';
$language['NOT_POSS_RESET_PID']='Není možné resetovat vaše PID! <br />Kontaktujte administrátora...';
$language['NOW_LOGIN']='Nyní budete požádán o přihlášení';
$language['NUMBER_SHORT']='#';
$language['OLD_PWD']='Staré heslo';
$language['ONLY_REG_COMMENT']='Pouze registrovaný uživatel může vložit komentář!';
$language['OPT_DB_RES']='Výsledek optimalizace databáze';
$language['OPTION']='Volba';
$language['PASS_RESET_CONF']='reset hesla potvrzen';
$language['PEER_CLIENT']='Klient';
$language['PEER_COUNTRY']='Země';
$language['PEER_ID']='Peer ID';
$language['PEER_LIST']='Seznam peerů';
$language['PEER_PORT']='Port';
$language['PEER_PROGRESS']='Stav';
$language['PEER_STATUS']='Status';
$language['PEERS']='Spojení';
$language['PEERS_DETAILS']='Klikněte pro zobrazení detailu peerů';
$language['PICTURE']='Obrázek';
$language['PID']='PID';
$language['PLEASE_WAIT']='Čekejte prosím...';
$language['PM']='PM';
$language['POSITION']='Pozice';
$language['POST_REPLY']='Odpovědět';
$language['POSTED_BY']='Odeslal';
$language['POSTED_DATE']='Odesláno';
$language['POSTS']='Příspěvky';
$language['POSTS_PER_DAY']='Příspěvků denně';
$language['POSTS_PER_PAGE']='Příspěvků na stránku';
$language['PREVIOUS']='Předch.';
$language['PRIVATE_MSG']='Soukromá zpráva (PM)';
$language['PWD_CHANGED']='Heslo změněno!';
$language['QUESTION']='Otázka';
$language['QUICK_JUMP']='Rychlý skok';
$language['QUOTE']='Citovat';
$language['RANK']='Hodnost';
$language['RATIO']='Ratio';
$language['REACHED_MAX_USERS']='Maximální množství uživatelů dosaženo';
$language['READED']='Přečteno';
$language['RECEIVER']='Příjato';
$language['RECOVER_DESC']='Použijte formulář níže pro reset vašeho hesla a detaily vašeho účtu vám budou zaslány mailem.<br />(Budete muset odpovědět na ověřovací email.)';
$language['RECOVER_PWD']='Obnovit heslo';
$language['RECOVER_TITLE']='Obnovit ztracené uživatelské jméno nebo heslo';
$language['REDIRECT']='Pokud Váš prohlížeč nepodporuje Javascript]= Klikněte';
$language['REDIRECT2']='Pokud Váš prohlížeč nepodporuje Javascript]= Klikněte <a href="%s">Tady</a>.';
$language['REDOWNLOAD_TORR_FROM']='Znovu stáhní torrent z';
$language['REGISTERED']='Registrovan';
$language['REGISTERED_EMAIL']='Registrační email';
$language['REMOVE']='Odstranit';
$language['REPLIES']='Odpovědi';
$language['REPLY']='Odpověď';
$language['RESULT']='Výsledek';
$language['RETRY']='Opakovat';
$language['RETURN_TORRENTS']='Zpět do seznamu torrentů';
$language['REVERIFY_CONGRATS1']='<center><br />Gratulujeme]= Váš email byl ověřen a úspěšně změněn<br /><br /><strong>Od: <font color="red">';
$language['REVERIFY_CONGRATS2']='</strong></font><br /><strong>Komu: <font color="red">';
$language['REVERIFY_CONGRATS3']='</strong></font><br /><br />';
$language['REVERIFY_FAILURE']='<center><br /><strong><font color="red"><u>Sorry ale tato URL není platná</u></strong></font><br /><br />Nové náhodné číslo je generováno každý pokus o změnu Vaše emailu takže<br /> pokud vidíte tuto zprávu tak zkoušíte změnit svůj email<br /> více než jednou a používáte starou URL.<br /><br /><strong>Prosím čekejte dokud si nebudete uplně jistí že nepřišla Nejnovější URL<br />ověřovacím emailem a potom se pokuste změnit email znovu.</strong><br /><br />';
$language['REVERIFY_MSG']='Pokud se pokoušíte změnit Vaší emailovou adresu bude Vám zaslán ověřovací email na emailovou adresu na kterou chcete svůj email změnit.<br /><br /><font color="red"><strong>Emailová adresa kterou jste zadali nebude funkční dokud nepotvrdíte odkaz v ověřovacím emailu.</strong></font>';
$language['RIGHT']='Pravo';
$language['SEARCH']='Vyhledat';
$language['SEEDERS']='Seedů';
$language['SEEN']='Viděn';
$language['SELECT']='Vyber...';
$language['SENDER']='Odesílatel/Příjemce';
$language['SENT_ERROR']='Chyba odeslání';
$language['SHORT_C']='ST.'; //Shortname for Completed
$language['SHORT_L']='L'; //Shortname for Leechers
$language['SHORT_S']='S'; //Shortname for Seeders
$language['SHOUTBOX']='Pošta';
$language['SIZE']='Velikost';
$language['SORRY']='Sorry';
$language['SORTID']='Sortid';
$language['SPEED']='Rychlost';
$language['STICKY']='Sticky';
$language['SUB_CATEGORY']='Sub-Kategorie';
$language['SUBJECT']='Předmět';
$language['SUBJECT_MAX_CHAR']='Předmět je omezen na ';
$language['SUC_POST_SUC_EDIT']='Příspěvek byl úspěšně editován.';
$language['SUC_SEND_EMAIL']='Potvrzovací email byl odeslán na ';
$language['SUC_SEND_EMAIL_2']='Prosím vyčkejte několik minut pro přijetí mailu.';
$language['SUCCESS']='Vše OK';
$language['SUMADD_BUG']='Tracker bug calling summaryAdd';
$language['TABLE_NAME']='Jméno tabulky';
$language['TIMEZONE']='Časové pásmo';
$language['TITLE']='Název';
$language['TOP']='nahoru';
$language['TOP_10_ACTIVE']='10 Nejaktivnějších torrentů';
$language['TOP_10_BEST_SEED']='10 Torrentů s nejlepším seedem';
$language['TOP_10_BSPEED']='10 Torrentů s nejvyšší rychlostí';
$language['TOP_10_DOWNLOAD']='10 Největších Downloaderů';
$language['TOP_10_SHARE']='10 Nejlepších sdílejících ';
$language['TOP_10_UPLOAD']='10 Nejlepších Uploaderů';
$language['TOP_10_WORST']='10 Nejhorších sdílejících :-(';
$language['TOP_10_WORST_SEED']='10 Torrentů s nejhorším seedem';
$language['TOP_10_WSPEED']='10 Torrentů s nejhorší rychlostí';
$language['TOP_TORRENTS']='Nejvíce populární Torrenty';
$language['TOPIC']='Téma';
$language['TOPICS']='Témata';
$language['TOPICS_PER_PAGE']='Topiků na stránku';
$language['TORR_PEER_DETAILS']='Detaily peeru torrentu';
$language['TORRENT']='Torrent';
$language['TORRENT_ANONYMOUS']='Odeslat jako anonymní';
$language['TORRENT_CHECK']='Povolit traceru příjmat a používat informace z torrentů.';
$language['TORRENT_DETAIL']='Detaily torrentů';
$language['TORRENT_FILE']='Název Torrentu';
$language['TORRENT_SEARCH']='Vyhledat torrenty';
$language['TORRENT_STATUS']='Status';
$language['TORRENT_UPDATE']='Updatuji]= prosím čekejte...';
$language['TORRENTS']='Torrentů';
$language['TORRENTS_PER_PAGE']='Torrentů na stránku';
$language['TRACK_DB_ERR']='Tracker/database error. Detaily najdete v error logu.';
$language['TRACKER_INFO']=$users.' users]= tracking '.$torrents.' torrents ('.$seeds.' seeds]= '.$leechers.' leechers]= '.$percent.'%)';
$language['TRACKER_LOAD']='Zatížení trackeru';
$language['TRACKER_SETTINGS']='Natavení trackeru';
$language['TRACKER_STATS']='Statictika trackeru';
$language['TRACKING']='Tledování';
$language['TRAFFIC']='Traffic';
$language['UCP_NOTE_1']='Tady můžete ovládat Vaší Poštu]= psát PM ostatním uživatelům]=';
$language['UCP_NOTE_2']='Ovládat a měnit Vaše nastavení]= atd...';
$language['UNAUTH_IP']=' Neautorizovaná IP Adresa.';
$language['UNKNOWN']='nezjištìný';
$language['UPDATE']='Update';
$language['UPFAILED']='Upload selhal';
$language['UPLOAD_IMAGE']='Upload obrázku';
$language['UPLOAD_LANGUAGE_FILE']='Upload souboru Language (jazyku)';
$language['UPLOADED']='Uploadoval';
$language['UPLOADER']='Uploader';
$language['UPLOADS']='Uploady';
$language['URL']='URL';
$language['USER']='Uživatel';
$language['USER_CP']='PROFIL';
$language['USER_CP_1']='Uživatelský panel';
$language['USER_DETAILS']='Detaily uživatele';
$language['USER_EMAIL']='Platný email';
$language['USER_ID']='ID uživatele';
$language['USER_JOINED']='Registován';
$language['USER_LASTACCESS']='Poslední návštěva';
$language['USER_LEVEL']='Hodnost';
$language['USER_LOCAL_TIME']='Nastavení časového pásma';
$language['USER_NAME']='Uživatel';
$language['USER_PASS_RECOVER']='Obnova hesla uživatele';
$language['USER_PWD']='Heslo';
$language['USERS_SEARCH']='Vyhledávání uživatelů';
$language['VIEW_DETAILS']='Zobrazit detaily';
$language['VIEW_TOPIC']='Zobrazit topik';
$language['VIEW_UNREAD']='Zobrazit nepřečtené';
$language['VIEWS']='Zobrazení';
$language['VISITOR']='Návštěvník';
$language['VISITORS']='Návštěvníci';
$language['WAIT_ADMIN_VALID']='Měly by jste počkat na schválení administrátory...';
$language['WARNING']='Varování!';
$language['WELCOME']='Vítejte';
$language['WELCOME_ADMINCP']='Administrace';
$language['WELCOME_BACK']='Vítejte zpět';
$language['WELCOME_UCP']='Vítejte v Uživatelském kontrolním panelu';
$language['WORD_AND']='a';
$language['WORD_NEW']='Nová';
$language['WROTE']='Napsal';
$language['WT']='WT';
$language['X_TIMES']='čas';
$language['YES']='Ano';
$language['LAST_IP']='Poslední IP';
$language['FIRST_UNREAD']='Přejdi na první nepřečtenou zprávu  Goto the first unread post';
$language['MODULE_UNACTIVE']='Požadovaný Modul není aktivní  The module required is not active!';
$language['MODULE_NOT_PRESENT']='Požadovaný Modul neexistuje!';
$language['MODULE_LOAD_ERROR']='Požadovaný Modul se zdá být chybný!';
$language["BONUS_INFO1"]="Ahoj tady můžeš vyměnit své body za seed (Tvůj stav ";
$language["BONUS_INFO2"]="(Pokud jsou tlačítka neaktivní, tak nemáš dostatek bodů ke směně!)";
$language["BONUS_INFO3"]="Jak můžu získat více bodů?<br>Za každou hodinu tvého seedu dostaneš ";
$language["BONUS_INFO4"]=" bodů za torrent.";
$language["WHAT_ABOUT"]="Co můžu všechno získat?";
$language["POINTS"]="Bodů";
$language["EXCHANGE"]="Vyměnit";
$language["GB_UPLOAD"]=" GB Uploadu";
$language["CHANGE_CUSTOM_TITLE"]="Změnit Osobní Titul(Cena - ";
$language["NO_CUSTOM_TITLE"]="žádný nemáš";
$language["UP_TO_VIP"]="Povýšit na hodnost VIP";
$language["NEED_MORE_POINTS"]="[Potřebuješ více bodů]";
$language["CHANGE_USERNAME"]="Změna nicku (Cena - ";
$language["IMDB"]="Filmy: IMDb URL:";
$language["RULES_SORT"]="Třídit pravidla";
$language["RULES"]="Pravidla";
$language["RULE"]="Pravidlo";
$language["RULE_ALL"]="Všechny pravidla";
$language["MNU_RULES"]="Pravidla";
$language["RULES_ADD"]="Nové pravidlo";
$language["MNU_FAQ"]="Nápověda";
$language["FAQ_NAME"]="Jméno skupiny";
$language["FAQ_TEXT"]="Popis skupiny";
$language["FAQ_SORT_INDEX"]="Třídit Faq ";
$language["FAQ_ADD"]="Vložit skupiny";
$language["FAQ_QUESTION"]="Otázka";
$language["FAQ_ANSWER"]="Odpověď";
$language["FAQ_QUESTION_ADD"]="Vložit Otázku/Odpověď";
$language["FAQ_QUESTION_SEARCH_ALL"]="Najít vše...";
$language["NOT_USER_CLASS"]="<h2>Sorry</h2><p>Musíte být registrování pro nákup tiketu.</p>";
$language["CANNOT_SELL_CLOSED"]="Sorry]= Nemůžu prodat žádné tikety! Loterie je uzavřena!";
$language["LOTTERY"]="LOTERIE";
$language["LOTT_LIMIT_PURCHASE"]="Maximální množství lístků  které můžete koupit je";
$language["LOTT_LIMIT_BUY"]="Maximální množství tiketků které si můžete koupit je";
$language["LOTTERY_PM_SUBJECT"]="Vyhrál jsi cenu v loterii";
$language["LOTTERY_PM_MESSAGE"]="Gragulujeme !!! vyhrál jsi cenu v naší Loterii. Tvoje výhra byla přidána na tvůj účet.";
$language["INVITE_CODE"]="Kód pozvánky";
$language["EMAIL_INACTIVE_SUBJ"]="Nemáš platný účet na $SITENAME .";
$language["EMAIL_INACTIVE_MSG"]="Ahoj \n\nTento email ti byl zaslán protože jsi dlouhou dobu nenavštívil náš tracker a byl jsi systémem vyhodnocen jako neaktivní člen.\nTvůj účet je nyní blokován a brzy dojde k jeho vymazání. \n\nPřejeme hezký den tvůj ModTeam.";
$language["DISABLE_STATS_COUNT"]="Deaktivace počítání";
$language["STATS_COUNT"]="Počítání";
$language["LEVEL_VISIBILE"]="Viditelný pro";
$language["AND_HIGHER"]="a vyšší";
$language["SPEED"]="Rychlost!";
$language["SPEEDTEST"]="Test rychlosti";
$language["ERR_REASON"]="Důvod smazání torrentu musí byt uveden";
$language["TOR_NOT_FOUND"]="nebylo nalezeno.";
$language["REASON_SUBJECT"]="Váš torrent byl vymazán";
$language["BODY_HI1_REASON"]="Ahoj";
$language["BODY_HI2_REASON"]="Tvůj torrent";
$language["BODY_HI3_REASON"]="byl smazan z trackeru členem";
$language["BODY_HI4_REASON"]=" z následujícího důvodu";
$language["REASON"]="Důvod";
$language["ACP_WARNEDU"]= "Seznam varovaných členů";
$language["DISABLE_ACCOUNT"]="Blokace účtu";
$language["ENABLE_ACCOUNT"]= "Odblokování účtu";
$language["ERR_ACCOUNT_DISABLED"]= "Upozornění: Tento účet je blokován !";
$language["ONE_WEEK"]= "1 týden";
$language["TWO_WEEKS"]= "2 týdny";
$language["THREE_WEEKS"]= "3 týdny";
$language["FOUR_WEEKS"]= "4 týdny";
$language["PERMANENTLY"]= "trvale";
$language["WARN_FALSE"]= "Ne";
$language["WARN_TRUE"]= "Ano";
$language["WARN_CONFIRM"]= "Jsi si jistý že chceš udělit varování tomuto uživateli ?";
$language["WARN_REMOVE"]= "Jsi si jistý že chceš odebrat varování tomuto uživateli ?";
$language["WARN_LEVEL_RESET"]= "Resetovat počet varování tohoto uživatele ?";
$language["WARN_DISABLE_ACCOUNT"]="Jsi si jistý že chceš zablokovat účet tohoto uživatele ?";
$language["WARN_ENABLE_ACCOUNT"]= "Jsi si jistý že chceš odblokovat účet tohoto uživatele ?";
$language["WARNED_USERS"]= "Uživatelé s varováním";
$language["DELETE"]= "Smazat";
$language["FILTR_CAT"]="Filtr kategorií: <br> (Vyber kategorii kterou chces vypnout)";
$language["DONATE"]="Příspěvky";


$language["MNU_UCP_INVITATIONS"]= "Pozvánky";
$language["MEMBERS_INVITED_BY"]= "Uživatele pozval ";
$language["SEND_INVITE"]= "Odeslat pozvánku";
$language["REMAINING"]= "máš k dispozici";
$language["CURRENT_INVITES_CONFIRMED"]="Seznam úspěšně potvrzených pozvánek";
$language["NO_INVITES_YET"]= "Nemáž žadnou pozvánku";
$language["STATUS"]= "Status";
$language["CONFIRMED"]= "Potvrzena";
$language["INVITES_NEED_CONFIRM"]= "Invites needing confirm";
$language["CURRENT_INVITES_NEED_CONFIRM"]= "Seznam úspěšně potvrzených pozvánek";
$language["NO_NEED_CONFIRM_YET"]= "No invites to confirm yet";
$language["PENDING"]= "Pending";
$language["INVITES_OUT"]= "Pozvánka byla odeslána";
$language["SEND_DATE"]= "Datum odeslání";
$language["CURRENT_INVITES_OUT"]= "Seznam odeslaných pozvánek";
$language["NO_INVITES_OUT"]= "Nyní nemáš odeslánou žádnou pozvánku";
$language["INVITE_SOMEONE_TO"]= "Pozvat někoho k připojení se k $SITENAME";
$language["INVITATION"] ="Pozvánky";
$language["MESSAGE"]= "Zpráva";
$language["INVALID_INVITE"]= "Pozvánka je neplatná";
$language["ERR_INVITE"]= "Hey! Ty nejsi pozvaný. Tak koukej odejít....";
$language["WELCOME_INVITE"]= "Vítáme tě! Akceptoval jsi zaslanou pozvánku. Nyní se můžeš registrovat";
$language["EMAIL_INVALID"]= "Špatný E-mail!";
$language["ERR_EMAIL_ALREADY_EXISTS"]= "Tento e-mail již v systému existuje !";
$language["ERR_MISSING_DATA"]= "Nedostupné informace !";
$language["INSERT_EMAIL"]= "Je zapotřebí vložit emailovou adresu !";
$language["INSERT_MESSAGE"]= "Prosím přidejte PM !";
$language["INVITE_EMAIL_SENT1"]= "Potvrzovací email byl zaslán na vloženou emailovou adresu";
$language["INVITE_EMAIL_SENT2"]= "Bude zapotřebí počkat dokud ten kdo Vám pozval nepotvrdí Váš účet.";
$language["INVITE_EMAIL_SENT3"]= "Email byl zaslán na uvedenou adresu";
$language["INVITE_EMAIL_SENT4"]= "Hodně štěstí a zábavy na $SITENAME !";
$language["PASSWORD_NOT_USERNAME"]= "Sorry]= ale heslo nemůže být stejné jako nick.";
$language["ERR_IP_ALREADY_EXISTS"]= "IP adresu již používá jiný uživatel!";
$language["ACCOUNT_CONFIRMED"]= "Schválování účtů";
$language["INVIT_CONFIRM"]= "POZVÁNKA";
$language["REG_CONFIRM"]= "Schválování registrací";
$language["VALID_INV_MODE"]= "Potřebujete schválení pozvánky Need confirm the invite";
$language["NO_INV"]= "Nemáte další pozvánky]= sorry.";
$language["INVITE_TIMEOUT"]= "Datum pozvánky expiroval<br />( den )";
$language["INVITES_OFF"]= "Pozvánky nejsou povolenéInvites aren't enable";
$language["INVIT_MSGCONFIRM"]= "Ahoj,\n\nTvůj účet byl potvrzený. Nyní můžeš navštívít\n\n$BASEURL/?page=login\n\na použij svoje přihlašovací pro přihlášení. Doufáme že jste si přečetl FAQ' a Pravidla předtím než začnete sdílet svá data !\n\n Hodně štěstí a zábavy na $SITENAME !\n\n\n----------------\nPokud jste se neregistrovaly na $SITENAME]= Prosím přepoštete tento email na $SITEEMAIL";
$language["INVIT_MSG_AUTOCONFIRM"]= "Požadoval jste založení nového účtu na $SITENAME a uvedl jste\n tuto adresu (";
$language["INVIT_MSG_AUTOCONFIRM1"]= ") jako kontakt na Vás.\n\nInformace účtu:\n Uživatelské jméno:";
$language["INVIT_MSG_AUTOCONFIRM2"]= "Heslo:";
$language["INVIT_MSG_AUTOCONFIRM3"]= "----------------\nNyní můžete navštívít\n\n$BASEURL/?page=login\n\na použít svoje přihlašovací pro přihlášení. Doufáme že jste si přečetl FAQ' a Pravidla předtím než začnete sdílet svá data !\n\n Hodně štěstí a zábavy na $SITENAME !\n\n\n----------------\nPokud jste se neregistrovaly na $SITENAME]= Prosím přepoštete tento email na $SITEEMAIL";
$language["INVIT_MSG"]= "Ahoj\n\nByl jste pozván na $SITENAME komunitu uživatelem";
$language["INVIT_MSG1"]="Pokud si přejete akceptovat tuto pozvánku Prosím klikněte na tento odkaz:\n\n\n$BASEURL/?page=account&invitenumber=";
$language["INVIT_MSG2"]= "Bude potřeba akceptovat tuto pozvánku do 24 hodin nebo se stane pozvánka neplatnou.\nMy na $SITENAME doufáme že pozvánku příjmáš a připojíš se do naší skvělé komunity!\n\n PM od";
$language["INVIT_MSG3"]= "----------------\nPokud neznáte osobu která Vás pozvala prosím přepošlete tuto zprávu na $SITEEMAIL";
$language["INVIT_MSGINFO"]= "Požadoval jste založení nového účtu na $SITENAME a uvedl jste\n tuto adresu (";
$language["INVIT_MSGINFO1"]= ") jako kontakt na Vás.\n\nVáš účet čeká na schválení od uživatele který Vás pozval.\nDokud nebude Váš účet schválený]= Nebudete se moct přihlásit na tracker.\n\nInformace účtu:\nUživatelské jméno:";
$language["INVIT_MSGINFO2"]= "Heslo:";
$language["INVIT_MSGINFO3"]= "Bude potřeba akceptovat tuto pozvánku do 24 hodin nebo bude Váš účet.\nProsíme přečtete si PRAVIDLA a FAQ před tím než začtete pracovat na $SITENAME.\n----------------\nPokud jste se neregistrovali na $SITENAME]= prosíme přepošlete tento emal na $SITEEMAIL";
$language["ACTIVE_INVITES"]= "Aktivovat pozvánku :";
$language["PRIVATE_TRACKER"]= "Soukromý tracker:";
$language["PRIVATE_TRACKER_INFO"]= "Upozornění. Tracker je nyní privátní, registrace možna pouze na pozvánku, bylo dosazenu \maximálního počtu uživatelu\. à \"1\" !";
$language["ONLY_INVITES"]= "Pouze na pozvánky.";
$language["INVITATIONS"]= "Pozvánek";
$language["ERR_IP_ALREADY_EXISTS"]= "IP adresu již používá jiný uživatel!";

$language["CUSTOM_TITLE"]= "Titul";
$language["NO_CUSTOM_TITLE"]= "Titul je pro daného uživatele nedostupný";

$language["REQUEST"]= "Poptávka";
$language["REQUESTS"]= "Žádosti";
$language["offers"]= "Nabídka";
$language["offer"]= "Nabídka";
$language["DISPLAY"]= "Zobrazit";
$language["TYPE"]= "Typ";
$language["DATE_ADDED"]= "Přidáno";
$language["ADDED_BY"]= "Přidal";
$language["FILLED"]= "Vyřízeno";
$language["FILLED_BY"]= "Vyřídil";
$language["VOTES"]= "Hlasy";
$language["ADD_REQUESTS"]= "Přidej žádost";
$language["ADD_offers"]= "Přidej nabídku";
$language["SEND"]= "Odešli";
$language["INFO"]= "Info";
$language["VOTE_FOR_THIS"]= "Hlasuj pro tuto";
$language["GLASAJ"]= "Hlasuj";

$language["RSEED"]= "Žádost o RESEED";
$language["SOMEONERESEE421D"]= "Byla odeslána hromadná PM všem kdo torrent stáhnul.";
$language["SOMEONERESEED"]= "Pouze 1 za den lze žádat o RESEED";

$language["BAN_MAILS_INFO"]= "Týto e-maily jsou na trackeru blokovány.<br>Můžeš je však kdykoliv odblokovat";
$language["NO_BAN_MAILS"]= "Zatím nemáme žádné blokované e-maily";
$language["ACP_BAN_MAILS"]= "Blokované e-maily";
$language["WAS_BANNED_ALLREADY"]= "úspěšně zablokováno !!";
$language["BANNED"]= "blokovat !!";
$language["NEW_BANNED_MAILS"]= "nový e-mail.";
$language["SYSTEM"]= "System";
$language["EMAIL_BANNED"]= "Tento e-mail je zablokován.";


$language["TASK_MANAGER"]= "Manager úkolů";
$language["TASK_ID"]= "ID";
$language["TASK_NAME"]= "Jméno";
$language["TASK_DESCRIPTION"]= "Popis";
$language["TASK_COMMENT"]= "Komentář<br /><font size=\"-2\" color=\"darkgreen\">(Poslední komentář bude přepsán)</font>";
$language["TASK_LAST_COMMENT"]= "Poslední komentář";
$language["TASK_NO_LAST_COMMENT"]= "Zatím nebyl úkol komentován.";
$language["TASK_PRIORITY"]= "Priorita";
$language["TASK_CREATED"]= "Vytvořeno";
$language["TASK_STATUS"]= "Status";
$language["NO_TASKS"]= "V tuto chvíli nemáme žádne úkoly";
$language["TASK_ADD_NEW"]= "Přidat nový úkol";
$language["PRIORITY_V_HIGH"]= "Velmi důležité";
$language["PRIORITY_HIGH"]= "Důležité";
$language["PRIORITY_AVERAGE"]= "Středně důležité";
$language["PRIORITY_LOW"]= "Nízká";
$language["PRIORITY_V_LOW"]= "Nedůležité";
$language["TASK_WAITING"]= "Čeká na vyřízení";
$language["TASK_WORKING"]= "Zpracovává se";
$language["TASK_DONE"]= "Dokončeno";
$language["TASK_TOTAL"]= "Všechny úkoly";
$language["TASK_VIEW"]= "Zobrazený úkol";
$language["TASK_NOT_LEAVE_BLANK"]= "Můžeš úkoly opustit neni zde žádný.";
$language["TASK_DELETE_1"]= "Smazat";
$language["TASK_DELETE_2"]= "dokončený(é) úkoly.";
$language["TASK_DELETE_3"]= "dokončené úkoly.";

$language["TORRENT_REQUESTED"]= "Na přání";
$language["TORRENT_NUKED"]= "Nabídka";
$language["TORRENT_NUKED_REASON"]= "Důvod";


$language["ADDED_TO_FRIENDLIST"]= "Přidat do seznamu přátel";
$language["MEMBER_ALREADY_EXIST"]= "Tento kontakt již je v seznamu přátel.";
$language["MEMBER1"]= "Uživatel";
$language["ADDED_TO_YOUR_FRIENDLIST"]= "byl přidán(a) do seznamu přátel.";
$language["HERE"]= "zde";
$language["TO_VIEW_FRIENDLIST"]= "pro zobrazení seznamu přátel.";
$language["RETURN_USERS"]= "Zpět na seznam uživatelů";
$language["FRIENDLIST"]= "Přátelé";
$language["NOTHING_IN_FRIENDLIST"]= "Seznam přátel je prázdný";
$language["ADD_TO_FRIENDLIST"]= "Přidat do seznamu přátel";
$language["USER_ONLINE"]= "Přítel je online";
$language["USER_OFFLINE"]= "Přítel je offline";


$language["RWARN_STATUS"]= "Varován";
$language["RWARN_OLD"]= "Nízké ratio";
$language["RWARN_DATE"]= "Datum";
$language["RWARN_WARN"]= "Warn";
$language["RWARN_REMOVE"]= "Odebrat";
$language["RWARN_YES"]= "Ano";
$language["RWARN_NO"]= "Ne";
$language["RWARN_DELETE"]= "Smazat";
$language["RWARN_SHITLIST"]= "Černá listina";
$language["RWARN_USHITLIST"]= "Odebrat z černé listiny";
$language["RWARN_WARNING"]= "Varováni!Máš(nízké ratio) tvůj účet je nyní na černé listině a hrozí ti blokace, proto ratio srovnej.";
$language["RWARN_MSG"]= "Varováni! Tvé ratio je nízké. Tvůj účet je nyní na černé listině a hrozí ti blokace, proto ratio srovnej.";
$language["RWARN_SUBJECT"]= "Varování za nízké ratio!";
$language["RWARN_VRATIO"]= "Zobrazit Ratio";
$language["RWARN_VWARNED"]= "Zobrazit varované";
$language["RWARN_VWARN"]= "Správa varovaných uživatelů";
$language["RWARN_VMSG"]= "Vyplň hodnotu ratia, a vyhledej uživatele:";
$language["RWARN_VBUT"]= "Zobrazit";
$language["RWARN_WARNED"]= "Varovaní uživatelé";
$language["RWARN_PRUNE"]= "Omezení uživatelé";
$language["RWARN_REMOVED"]= "Odebrat varování";
$language["RWARN_USL"]= "Resetovat uživatele";
$language["RWARN_SL"]= "Uživatelé na černé listině";
$language["SORT_BY"]= "Seřadit podle";

$language["ERR_IP_ALREADY_EXISTS" ]="<br><img src=image/shared_ip.gif border=0><br>";

$language['IGN_OTHER']='Ostatní';
$language['LIST_IGNORE']='Ignorace';
$language['IGNORE1']='Ignorovaní uživatelé';
$language['IGNORE2']='Povolit odeslání';
$language['IGNORE_USERS']='Ignorovaný uživatel';
$language['SINCE_IGNORE']='Od kdy je ignorován';
$language['DELETE_IGNORE']='Zrušit ignoraci';


// begin modification
// hack: MAC Address Tools - Works with Java 6+ supported browsers
// operation #0
// Begin: Ban by MAC Address Hack
$language['LAST_MAC']='Last MAC Address(es):';
// End: Ban by MAC Address Hack 


// end modification
// hack: MAC Address Tools - Works with Java 6+ supported browsers
// operation #0

// begin modification
// hack: Detect & Blacklist Proxy
// operation #0

$language['CHANGE_CONFIRM']='Are you sure you want to change this users download rights?';
$language['CHANGED']='Change';

// end modification
// hack: Detect & Blacklist Proxy
// operation #0

?>
