<?php
$language['DELETE_READED']='Smazat';
$language['USER_LANGUE']='Jazyk';
$language['USER_STYLE']='Styl';
$language['CURRENTLY_PEER']='Vaš aktuální seed a leech torrentů.';
$language['STOP_PEER']='Musíte zastavit vašeho klienta.';
$language['USER_PWD_AGAIN']='Opakujte heslo';
$language['EMAIL_FAILED']='Odesílání emailu selhalo!';
$language['NO_SUBJECT']='Žádný předmět';
$language['MUST_ENTER_PASSWORD']='<br /><font color="#FF0000"><strong>Musíte vložit Vaše heslo pro změnu nastavení.</strong></font>';
$language['ERR_PASS_WRONG']='Heslo je prázné nebo špaté, nemohu updatovat Váš profil.';
$language['MSG_DEL_ALL_PM']='Pokud vyberete PM které nejsou přečteny, nebudou smazány';
$language['ERR_PM_GUEST']='Sorry, ale nemůžeš poslat PM questu nebo sám sobě!';
$language["ACTIVE_TORRENT"]= "Aktivní torrent";
$language["MNU_UCP_RENAME"]="Změnit uživatelské jméno";
$language["CURR_NICK"]="Současné uživatelské jmého";
$language["NEW_NICK"]="Nové uživatelské jméno";
$language["REPEAT_NICK"]="Opakujte nové uživatelské jméno";
$language["ERR_NICK_NO_MATCH"]="Uživatelské jméno nesouhlasí";
$language["ERR_SAME_NICK"]="Váše uživatelské jméno je již";
$language["ERR_NICK_TOO_SMALL"]="Vaše nové uživatelské jméno musí mít nejméně 3 znaky";
$language["ERR_NICK_NOT_ALLOWED"]="Toto uživatelské jméno není povoleno";
$language["NICK_CHANGE_SUCCESS"]="Nyní jste si úspěšně změnily uživatelské jméno na ";
$language["CHANGED_THEIR_NICK"]="Změnit jejich uživatelské jméno na ";
$language["CHANGE_NICKNAME"]="Změnit uživatelské jméno";
$language["INVITE_GEN"]="Generátor pozvánek";
$language["SUBSCRIBE"]="Sledování torrentu";
$language["SUB_OK"]="Váš výběr sledovaných kategorií torrentů byl uložen <a href=\"index.php?page=usercp&amp;do=subscribe&amp;action=change&amp;uid=".$CURUSER["uid"]."\">výběr kategorie</a>";
$language["SUB_SUBJECT"]="Sledované torrenty z $SITENAME";
$language["SUB_EMAIL"]="Dobrý den,\nA nový torrent \"%s\" byl uploadován do Vámi sledované kategorie torrentů \n\nDetail: %s\nStaženi: %s\n\nPříjemné stahování\n$SITENAME";
$language["MNU_UCP_AVATAR"] = "Nahrát Avatar";
$language["AVATAR_SUCCESS"] = "Váš Avatar byl v pořádku nahrán!";
$language["AVATAR_FAILURE1"] = "Chyba. Avatar je příliš velký! Zvol povolenou velikost";
$language["AVATAR_FAILURE2"] = "Chyba. Avatar je příliš velký! Limit je";
$language["AVATAR_FAILURE3"] = "Chyba. Neznámá chyba!";
$language["AV_FEW_HEAD"] = "Kritéria pro nahráni Avatara";
$language["AV_FILE_SIZE"] = "Nenahrávejte soubory větší než";
$language["AV_IMAGE_SIZE"] = "Nenahrávejte Avatary, které jsou větší než";
$language["AV_FORBIDDEN"] = "Nenahrávejte další Avatary";
$language["AV_NO_HEADER"] = "Váš Avatar jste již nahráli. Nemůžete nahrávat další.";
$language["AV_NO_1"] = "Váš Avatar byl už nahrán";
$language["AV_NO_2"] = "Smazat Avatar";
$language["AV_NO_3"] = "Odkaz na Avatar";
?>